[package]
name = "owl-memory"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

description = "Memory tracking interfaces for OwL Browser."

[dependencies]
tabs = { path = "../tabs", package = "owl-tabs" }
