[package]
name = "owl-tabs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

description = "Tab lifecycle and state management for OwL Browser."

[dependencies]
util = { path = "../util", package = "owl-util" }
